apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: schema-registry
  labels:
    app: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081

---
# PodDisruptionBudget для обеспечения доступности при обновлениях и сбоях
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: schema-registry-pdb
  namespace: schema-registry
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: schema-registry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: schema-registry
  labels:
    app: schema-registry
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: schema-registry
                topologyKey: kubernetes.io/hostname
      containers:
        - name: schema-registry
          image: ghcr.io/aiven-open/karapace:5.0.3
          imagePullPolicy: IfNotPresent
          command: ["python3", "-m", "karapace.__main__"]
          ports:
            - containerPort: 8081
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: KARAPACE_KARAPACE_REGISTRY
              value: "true"
            - name: KARAPACE_KARAPACE_REST
              value: "false"
            - name: KARAPACE_HOST
              value: "0.0.0.0"
            - name: KARAPACE_PORT
              value: "8081"
            - name: KARAPACE_ADVERTISED_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KARAPACE_BOOTSTRAP_URI
              value: kafka-cluster-kafka-bootstrap.kafka-cluster:9092
            - name: KARAPACE_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: KARAPACE_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: KARAPACE_SASL_PLAIN_USERNAME
              value: "schema-registry"
            - name: KARAPACE_SASL_PLAIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: schema-registry
                  key: password
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KARAPACE_CLIENT_ID
              value: "$(POD_NAME)"
            - name: KARAPACE_GROUP_ID
              value: "schema-registry"
            - name: KARAPACE_TOPIC_NAME
              value: "_schemas"
          readinessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
