apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: schema-registry
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Права на уровне кластера, требуемые некоторыми Kafka клиентами (например, idempotent producer)
      - resource:
          type: cluster
        operations:
          - Describe
          - IdempotentWrite
      # Karapace (совместим с Schema Registry API) хранит схемы в Kafka топике `_schemas`
      - resource:
          type: topic
          name: _schemas
          patternType: literal
        operations:
          - Read
          - Write
          - Create
          - Describe
          - DescribeConfigs
          - AlterConfigs
      # Consumer group, используемая Schema Registry
      - resource:
          type: group
          name: schema-registry
          patternType: literal
        operations:
          - Read
          - Describe
      # Karapace может создавать автосгенерированные consumer groups (FindCoordinator использует DESCRIBE для группы)
      - resource:
          type: group
          name: karapace-autogenerated-
          patternType: prefix
        operations:
          - Read
          - Describe
