apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: schemas-topic
  namespace: myproject
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: _schemas
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact
