apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      strimzi.io/kind: KafkaExporter
  namespaceSelector:
    matchNames:
      - myproject
  endpoints:
    - port: metrics
      path: /metrics
